server:
  port: ${PORT}

spring:
  application:
    name: ms-notification
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

adapters:
  sns:
    region: ${AWS_SNS_REGION}

logging:
  level:
    com:
      foodcourt: ${LOG_LEVEL:-INFO}
    org:
      hibernate:
        orm:
          connections:
            pooling: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}